name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db_graphql:
        image: postgres:13-alpine
        env:
          HOST_PORT: ${{ env.test.HOST_PORT }}
          POSTGRES_USER: ${{ env.test.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.test.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.testPOSTGRES_DB }}
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python test.py
