name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db_graphql:
        image: postgres:13-alpine
        env:
          HOST_PORT: 5000
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: testPass
          POSTGRES_DB: graphql_db
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env:
          HOST_URL: localhost
          HOST_PORT: 5000
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: testPass
          POSTGRES_SERVER: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: graphql_db
        run: |
          python test.py
