name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.test.HOST_URL }}

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db_graphql:
        image: postgres:13-alpine
        env:
          HOST_PORT: ${{ github.env.test.HOST_PORT }}
          POSTGRES_USER: ${{ github.env.test.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ github.env.test.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ github.env.test.POSTGRES_DB }}
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Use variables
        run: |
          echo "HOST_PORT variable : $HOST_PORT"
          echo "POSTGRES_USER variable : $POSTGRES_USER"
          echo "POSTGRES_PASSWORD variable : $POSTGRES_PASSWORD"
          echo "variable from shell environment : $env_var"
        env:
          HOST_PORT: ${{ github.env.test.HOST_PORT }}
          POSTGRES_USER: ${{ github.env.test.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ github.env.test.POSTGRES_PASSWORD }}

      - name: Run Tests
        env:
          HOST_URL: ${{ github.env.test.HOST_URL }}
          HOST_PORT: ${{ github.env.test.HOST_PORT }}
          POSTGRES_USER: ${{ github.env.test.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ github.env.test.POSTGRES_PASSWORD }}
          POSTGRES_SERVER: ${{ github.env.test.POSTGRES_SERVER }}
          POSTGRES_PORT: ${{ github.env.test.POSTGRES_PORT }}
          POSTGRES_DB: ${{ github.env.test.POSTGRES_DB }}
        run: |
          python test.py
