name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: test
    services:
      db_graphql:
        image: postgres:13-alpine
        env:
          HOST_PORT: ${{ vars.HOST_PORT }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Use variables
        run: |
          echo "HOST_PORT variable : $HOST_PORT"
          echo "POSTGRES_USER variable : $POSTGRES_USER"
          echo "POSTGRES_PASSWORD variable : $POSTGRES_PASSWORD"

        env:
          HOST_PORT: ${{ vars.HOST_PORT }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}

      - name: Run Tests
        env:
          HOST_URL: ${{ vars.HOST_URL }}
          HOST_PORT: ${{ vars.HOST_PORT }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
          POSTGRES_SERVER: ${{ vars.POSTGRES_SERVER }}
          POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
        run: |
          python test.py
